name: algolia_helper_flutter
description: Patterns and APIs to implement advanced search features with Algolia for Flutter
version: 1.0.0
homepage: https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/flutter/
repository: https://github.com/algolia/algoliasearch-helper-flutter/tree/main/helper
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  algolia_insights: ">=1.0.0 <2.0.0"
  algoliasearch: ">=1.3.0 <2.0.0"
  collection: ">=1.17.0 <2.0.0"
  flutter:
    sdk: flutter
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.11.0 <2.0.0"
  rxdart: ">=0.26.0 <1.0.0"
dev_dependencies:
  build_runner: ">=2.4.0 <3.0.0"
  flutter_lints: ">=3.0.0 <4.0.0"
  flutter_test:
    sdk: flutter
  lints: ">=3.0.0 <4.0.0"
  mockito: ">=5.4.0 <6.0.0"
  provider: ">=6.1.0 <7.0.0"
  test: ">=1.25.0 <2.0.0"
