name: algolia_helper_dart
description: Algolia Dart Helper
version: 0.0.1
homepage: https://github.com/algolia/algoliasearch-helper-dart/helper_dart

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  algolia: ^1.1.1
  rxdart: ^0.27.4
  logging: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.12
