name: algolia_insights
description: Algolia Insights for Dart provides a simple and flexible way to track events such as clicks, conversions, and views on search results.
version: 0.1.2
homepage: https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/flutter/
repository: https://github.com/algolia/algoliasearch-helper-flutter/tree/main/insights_dart

environment:
  sdk: ">=2.17.5 <4.0.0"
  flutter: '>=1.17.0'
dependencies:
  algolia_client_insights: ^0.1.1+3
  collection: ^1.16.0
  hive: ^2.2.3
  logging: ^1.0.2
  meta: ^1.7.0
  path_provider: ^2.0.15
  rxdart: ^0.27.4
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.4.4
  lints: ^2.1.0
  mockito: ^5.4.0
  test: ^1.24.0
  test_api: ">=0.2.1 <0.6.0"
