name: algolia_insights
description: Algolia Insights Helper for Dart
version: 0.0.1
homepage: https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/flutter/
repository: https://github.com/algolia/algoliasearch-helper-flutter/tree/main/insights_dart

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  algolia: ^1.1.1
  collection: ^1.16.0
  logging: ^1.0.2
  meta: ^1.7.0
  rxdart: ^0.27.4

dev_dependencies:
  build_runner: 2.2.0
  lints: ^2.0.0
  mockito: ^5.3.0
  test: ^1.17.12
