name: algolia_helper_flutter
description: Patterns and APIs to implement advanced search features with Algolia for Flutter
version: 0.2.0
homepage: https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/flutter/
repository: https://github.com/algolia/algoliasearch-helper-flutter/tree/main/helper_flutter

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  algolia_helper: ^0.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  provider: ^6.0.3
